theme: jekyll-theme-cayman
destination: ./scl
title: Sequential Contrastive Learning to Master Effective Representations For Reinforcement Learning and Control
description: Ali Younes, and Alexandr Panov
